<?php

namespace Packed\Bundle\ScoreModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InhoudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InhoudRepository extends EntityRepository
{
}
