parameters:
     score_model.utils.tekengrafiek.class: Packed\Bundle\ScoreModelBundle\Utils\TekenGrafiek
#    score_model.example.class: Packed\Bundle\ScoreModelBundle\Example

services:
     score_model.utils.tekengrafiek:
         class: %score_model.utils.tekengrafiek.class%

#    score_model.example:
#        class: %score_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
